name: Trigger auto deployment for recipe-generator-frontend-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/recipe-generator-frontend-app-AutoDeployTrigger-ac0eb01f-d3b4-4c67-8d9a-609dd328277d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RECIPEGENERATORFRONTENDAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RECIPEGENERATORFRONTENDAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RECIPEGENERATORFRONTENDAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.RECIPEGENERATORFRONTENDAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RECIPEGENERATORFRONTENDAPP_REGISTRY_PASSWORD }}
          containerAppName: recipe-generator-frontend-app
          resourceGroup: recipe-generator
          imageToBuild: ili16/recipe-generator-frontend-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


